### ISSUE TITLE
Classification from HDR

### ISSUE THREAD

**Issue by noelpimentel** [berkeley-stat159/project-kappa#78] opened 2015-12-05 06:16 UTC
@matthew-brett @rossbar 

Would the pattern of response we obtain from finding the times of activation from the HDR be our classifiers. I attached a drawing to provide a visual. Are we going in the right direction or should we scrape this idea?

![img_0950](https://cloud.githubusercontent.com/assets/14045914/11606377/0153dd7c-9ad4-11e5-92b1-ab7f88931b42.JPG)

**Comment by matthew-brett** [comment] 2015-12-05 09:08
I'm not sure I understand your idea here, but I still think that the first thing you should do, before anything else, is to make sure you can get activation maps for houses, faces etc for each subject, using the stuff from the class notes.  Have you got anywhere with that yet?

**Comment by noelpimentel** [comment] 2015-12-06 10:19
@matthew-brett 
We were able to get the activation map for houses so we'll be able to get the maps for the rest of the objects for every subject. I'm still a bit stumped on the method you explained to us on Thursday of obtaining the response variables for classification. Here's a rough image of the house activation map

![house_activation](https://cloud.githubusercontent.com/assets/14045914/11612837/985e99c4-9bbe-11e5-9e77-a11683459224.png)

**Comment by matthew-brett** [comment] 2015-12-07 18:22
Thanks for these plots.  I'm slightly worried that they don't look right - can you send me instructions on how to reproduce them?

I don't remember what I said about machine learning on Thursday (other than, concentrate on the activation maps first).  But, once you have the activation maps, and you have worked out a good way to combine them across subjects, you could then do something like feature reduction with PCA, to reduce the voxel dimension to a small number of components, and then taking the PCA weights during the different blocks.  But please get the activation maps fully done first, to make sure you've got something done and correct and reproducible.

**Comment by noelpimentel** [comment] 2015-12-07 18:48
@matthew-brett I was not using the preprocessed data could that have been an issue? Also, I did not apply the linear drift before the mapping. @changzheng1993 has the code for the linear drift and we're fixing a problem we found.  We'll integrate it to the mapping and we'll send code/script that we'll reproduce the maps shortly.

**Comment by matthew-brett** [comment] 2015-12-07 18:50
OK.  I'd recommend you concentrate on the preprocessed data because that will allow you to better compare across subjects.  You will certainly need the linear drift term.

**Comment by matthew-brett** [comment] 2015-12-12 20:37
Guys - OK to close this one?

**Closed as completed** 2015-12-12 21:18 UTC
